sudo: false
language: node_js
node_js:
  - "6"
  - "5"
  - "4"
env:
  - CC=clang CXX=clang++ npm_config_clang=1
addons:
  apt:
    packages:
    - libmagick++-dev
before_script:
  - npm install -g mocha
